In [30]:
import numpy as np
import torch
import torch.nn as torchNN
import matplotlib.pyplot as plt

%matplotlib inline

In [31]:
base = [[1, 2, 3], [4, 5, 6]]

v = torch.Tensor(base)
print(v.size())
print(v.shape[0])

print(v.view(3, 2))             # view -> reshape
print(v.view(-1))               # flatten all
print(torch.flatten(v))

print(v.view(v.size(0), -1))    # 类似与把每一个 batch 展平 (flatten)
print( torch.flatten(v, start_dim = 1 ) )           # 只把第一个维度展开 => 类似于 把每一个batch展平

test = torch.zeros(4, 5, 5)                         # shape -> (4, 5, 5) | (batchsize, height, weight)
print(test)

print(test.view(test.size(0), -1))                  # shape -> (4, 5 * 5)
print( torch.flatten(test, 1) )                     # shape -> (4, 5 * 5)

torch.Size([2, 3])
2
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([1., 2., 3., 4., 5., 6.])
tensor([1., 2., 3., 4., 5., 6.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.],
        [0., 0., 0., 