In [1]:
import torch
import numpy

# `Bool Index`

类似于一种 mask, 提供的 bool 为 True 则保留该元素, 若为 False, 则在副本中不包含此元素

其中 mask 的维度要与 data 的前 m 维度对应

In [12]:
data = torch.arange(24).reshape(4, 2, 3)

print(data)

mask1 = torch.tensor([True, False, True, False], dtype = torch.bool)
print(data[mask1])                              # 对 D_0 取
print(data[mask1].shape)

mask2 = torch.tensor([[True, False], [False, True], [True, False], [False, False]])
print(data[mask2])
print(data[mask2].shape)
# 相当于把前两个维度展开，然后按照 True 和 False 来取数, 所以返回值的 shape 为 [Number(True), data.size(2)]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[12, 13, 14],
         [15, 16, 17]]])
torch.Size([2, 2, 3])
tensor([[ 0,  1,  2],
        [ 9, 10, 11],
        [12, 13, 14]])
torch.Size([3, 3])


#  `条件索引`

在索引处传入条件表达式, 返回符合条件的数据, 并且展成 维度 m 的向量

In [15]:
print(data[data < 10].shape)

torch.Size([10])
