In [1]:
import numpy as np
import torch
import torch.nn as torchNN
import torch.nn.functional as torchF
import matplotlib.pyplot as plt

%matplotlib inline

In [22]:
# Tensor is not involved in the backward
v = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(type(v))

base1 = np.array([[1, 3, 5], [2, 3, 4]])

v = torch.Tensor(base1)
print(v)

u = torch.FloatTensor(base1)

print(v + u)
print(v * 2)

base2 = torch.rand(5)
print(base2)
print(base2.dot(torch.rand(5)))             # do not change the base2
print(base2)

<class 'torch.Tensor'>
tensor([[1., 3., 5.],
        [2., 3., 4.]])
tensor([[ 2.,  6., 10.],
        [ 4.,  6.,  8.]])
tensor([[ 2.,  6., 10.],
        [ 4.,  6.,  8.]])
tensor([0.2533, 0.5410, 0.7138, 0.2569, 0.7713])
tensor(1.2344)
tensor([0.2533, 0.5410, 0.7138, 0.2569, 0.7713])


In [35]:
from torch.autograd import Variable

v = Variable(v, requires_grad = True)
print(v)

loss = torch.mean(v ** 2)                # 1/n sigma(x_i ^ 2)
print(loss)
loss.backward()                         # 对 x 求梯度
print(v.grad)

tensor([[1., 3., 5.],
        [2., 3., 4.]], requires_grad=True)
tensor(10.6667, grad_fn=<MeanBackward0>)
tensor([[0.3333, 1.0000, 1.6667],
        [0.6667, 1.0000, 1.3333]])
